services:

  findwords-service:
    build: 
      context: .
      dockerfile: ./findwords-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - USE_CACHE=true